---

- name: Removing useless packages from the cache
  apt:
    autoclean: yes
  when: hm_cleanup__autoclean

- name: Removing dependencies that are no longer required
  apt:
    autoremove: yes
  when: hm_cleanup__autoremove

- name: Removing any unnecessary system packages
  apt:
    name: "{{ hm_cleanup__remove_packages[ansible_os_family|lower]['apt'] }}"
    state: absent
  when: "ansible_os_family|lower in hm_cleanup__remove_packages and 'apt' in hm_cleanup__remove_packages[ansible_os_family|lower]"

- name: Removing unnecessary files and folders
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ hm_cleanup__remove_files }}"
  when: item not in ["/","/bin","/boot","/lib","/root","/sbin","/usr","/var"]
